name: Linux
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Requirements
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y python3-pip wget
      - name: Build
        run: |
          wget -o /usr/local/bin/appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          pip3 install Gooey==1.2.0a0 yt-dlp ezpyi
          ezpyi -A yt-dlp-gui.py yt-dlp-gui.AppImage
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt-dlp-gui-Linux
          path: yt-dlp-gui.AppImage
          if-no-files-found: warn
