name: Linux
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install Requirements
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get full-upgrade -y
          sudo apt-get install -y wget git
      - name: Install Python 3.10
        run: |
          # Setup
          sudo apt update && sudo apt upgrade -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y

          # Python 3.10
          sudo apt install python3.10
          sudo apt install python3.10-dev
          sudo apt install python3.10-distutils
          sudo apt install python3.10-venv

          # Pip
          curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
          echo 'export PATH=$HOME/.local/bin:$PATH' >>~/.profile
          source ~/.profile
          pip install --upgrade pip

          # Remap
          sudo apt install python-is-python3
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
      - name: Build
        run: |
          wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
          sudo pip3.10 install wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
          sudo wget -o /usr/local/bin/appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          sudo pip3.10 install yt-dlp ezpyi
          git clone --recursive https://github.com/Xpl0itU/GooeyPlus
          sudo python3.10 GooeyPlus/setup.py install
          sudo ezpyi -A yt-dlp-gui.py yt-dlp-gui.AppImage
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt-dlp-gui-Linux
          path: yt-dlp-gui.AppImage
          if-no-files-found: warn
