name: Windows
on: push

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          pip3 install pyinstaller yt-dlp Gooey
          pyinstaller yt-dlp-gui.py
          Invoke-WebRequest -URI https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg
          copy ffmpeg/ffmpeg-5.1.2-essentials_build/bin/* dist/yt-dlp-gui
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: yt-dlp-gui-Windows
          path: dist/
          if-no-files-found: warn
